# Generated by Django 6.0.7 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('serveur', 'Serveur'), ('caisse', 'Caissier / POS')], default='serveur', max_length=20),
        ),
    ]
