# Generated by Django 6.0.7 on 2026-07-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("ordre_affichage", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["ordre_affichage"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("prix", models.DecimalField(decimal_places=0, max_digits=10)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="menu/")),
                ("disponible", models.BooleanField(default=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="menu.category",
                    ),
                ),
            ],
        ),
    ]
