# Generated by Django 6.0.7 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordre_affichage', 'nom'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-est_populaire', 'nom'], 'verbose_name_plural': 'Articles du Menu'},
        ),
        migrations.AddField(
            model_name='category',
            name='couleur_card',
            field=models.CharField(default='linear-gradient(135deg, #8E5CF7, #A881FC)', help_text='Dégradé CSS pour la carte publique', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='icone',
            field=models.CharField(default='fa-utensils', help_text='Nom de classe FontAwesome ou emoji', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='badge',
            field=models.CharField(blank=True, help_text='ex: HOT, NEW, -15%', max_length=30),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='est_populaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='est_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='note_etoiles',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='photo_url',
            field=models.URLField(blank=True, help_text="URL externe d'image haute qualité si pas d'upload", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
