# Generated by Django 6.0.7 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacite', models.PositiveIntegerField(default=4)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=20)),
                ('emplacement', models.CharField(default='Salle Principale', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tables',
                'ordering': ['numero'],
            },
        ),
    ]
