# Generated by Django 6.0.7 on 2026-07-31 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('chiffre_affaires', models.DecimalField(decimal_places=0, max_digits=14)),
                ('nombre_commandes', models.PositiveIntegerField(default=0)),
                ('ticket_moyen', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rapports Journaliers',
                'ordering': ['-date'],
            },
        ),
    ]
