# Generated by Django 6.0.7 on 2026-08-02 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date_debut'], 'verbose_name_plural': 'Rapports'},
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2026, 8, 2, 22, 58, 50, 777607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='date_fin',
            field=models.DateField(blank=True, help_text="Laisser vide pour un rapport d'une seule journée (= date_debut)", null=True),
        ),
    ]
