# Generated by Django 6.0.7 on 2026-07-31 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(editable=False, max_length=30, unique=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money (Wave / Orange / MTN)'), ('carte', 'Carte Bancaire')], default='especes', max_length=20)),
                ('montant_recu', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monnaie_rendue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encaisse_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus_encaisses', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Reçus Caisse (POS)',
                'ordering': ['-created_at'],
            },
        ),
    ]
